# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_project.ui'
#
# Created by: PyQt UI code generator, adapted for PyQt5 / PyQt6 compatibility
#
# WARNING: Any manual changes made to this file will be lost when pyuic is
# run again. Do not edit this file unless you know what you are doing.

from qgis.gui import QgsFileWidget
from qgis.PyQt import QtCore, QtWidgets
from ..qgis_lib_mc.qt_compatibility import *


class Ui_createProjetDialog(object):
    def setupUi(self, createProjetDialog):
        createProjetDialog.setObjectName("createProjetDialog")
        createProjetDialog.resize(358, 140)
        sizePolicy = QtWidgets.QSizePolicy(
            SIZEPOLICY_PREFERRED,
            SIZEPOLICY_FIXED,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            createProjetDialog.sizePolicy().hasHeightForWidth()
        )
        createProjetDialog.setSizePolicy(sizePolicy)
        createProjetDialog.setMaximumSize(QtCore.QSize(16777215, 140))
        createProjetDialog.setAccessibleName("Create new project")

        self.gridLayout = QtWidgets.QGridLayout(createProjetDialog)
        self.gridLayout.setObjectName("gridLayout")

        self.label_3 = QtWidgets.QLabel(createProjetDialog)
        self.label_3.setContextMenuPolicy(PREVENT_CONTEXT_MENU)
        self.label_3.setTextFormat(RICH_TEXT)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 3)

        self.label = QtWidgets.QLabel(createProjetDialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)

        self.workspaceDir = QgsFileWidget(createProjetDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            SIZEPOLICY_PREFERRED,
            SIZEPOLICY_FIXED,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.workspaceDir.sizePolicy().hasHeightForWidth()
        )
        self.workspaceDir.setSizePolicy(sizePolicy)
        self.workspaceDir.setMinimumSize(QtCore.QSize(0, 20))
        self.workspaceDir.setMaximumSize(QtCore.QSize(16777215, 25))
        self.workspaceDir.setObjectName("workspaceDir")
        self.gridLayout.addWidget(self.workspaceDir, 1, 2, 1, 1)

        self.label_2 = QtWidgets.QLabel(createProjetDialog)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)

        self.projectName = QtWidgets.QLineEdit(createProjetDialog)
        self.projectName.setMinimumSize(QtCore.QSize(0, 20))
        self.projectName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.projectName.setObjectName("projectName")
        self.gridLayout.addWidget(self.projectName, 2, 1, 1, 2)

        self.buttonBox = QtWidgets.QDialogButtonBox(createProjetDialog)
        self.buttonBox.setAccessibleName("")
        self.buttonBox.setOrientation(HORIZONTAL)
        self.buttonBox.setStandardButtons(CANCEL | OK)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 3)

        self.retranslateUi(createProjetDialog)
        self.buttonBox.accepted.connect(createProjetDialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(createProjetDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(createProjetDialog)

    def retranslateUi(self, createProjetDialog):
        _translate = QtCore.QCoreApplication.translate
        createProjetDialog.setWindowTitle(
            _translate("createProjetDialog", "Create new project")
        )
        self.label_3.setText(
            _translate(
                "createProjetDialog",
                "<html><head/><body><p>Workspace directory is used to store "
                "outputs from MitiConnect.<br/>Project file "
                "<span style=\" font-weight:600;\">Worskpace/ProjectName.xml</span> "
                "is initiialized.</p></body></html>",
            )
        )
        self.label.setText(_translate("createProjetDialog", "Workspace"))
        self.label_2.setText(_translate("createProjetDialog", "Project name"))


