# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ErcTvbPluginDialog
                                 A QGIS plugin
 MitiConnect integrates ecological Connectivity in Mitigation Hierarchy
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-08-25
        git sha              : $Format:%H$
        copyright            : (C) 2021 by INRAE
        email                : mathieu.chailloux@inrae.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os, sys, copy

from qgis.PyQt import uic, QtWidgets, QtCore
from qgis.core import QgsFieldProxyModel 

from ..qgis_lib_mc import (
    utils,
    abstract_model,
    qgsUtils,
    feedbacks,
    qgsTreatments,
    qt_compatibility)
from ..steps import friction
from . import scenario_dialog_ui

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
# SC_DIALOG, _ = uic.loadUiType(os.path.join(
#     os.path.dirname(__file__), 'scenario_dialog.ui'))
SC_DIALOG = scenario_dialog_ui.Ui_scenarioDialog
SC_LANDUSE_DIALOG, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'scenario_landuse_dialog.ui'))
SC_IS_DIALOG, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'scenario_initialState_dialog.ui'))

class ScenarioItem(abstract_model.DictItemWithChild):
    
    NAME = 'NAME'
    DESCR = 'DESCR'
    BASE = 'BASE'
    # SC_MODE = 'SC_MODE'
    BASE_LAYER = 'BASE_LAYER'
    LAYER = 'LAYER'
    EXTENT_FLAG = 'EXTENT_FLAG'
    # True = Field mode, False = Fixed mode
    MODE = 'MODE'
    RECLASS_FIELD = 'RECLASS_FIELD'
    # MODEL = 'RECLASS_VAL'
    MODEL = 'MODEL'
    BURN_VAL = 'BURN_VAL'
    # DISPLAY_FIELDS = ['NAME','BASE']
    
    LANDUSE_MODE = 0
    VECTOR_FIXED_MODE = 1
    VECTOR_FIELD_MODE = 2
    INITIAL_STATE_MODE = 3
    RASTER_VALUES_MODE = 4
    RASTER_FIXED_MODE = 5
    PONDERATION_MODE = 6

    SC_LANDUSE_MODE = 0
    SC_POND_MODE = 1
    
    BASE_FIELDS = [ NAME, DESCR, BASE ]
    RECLASS_FIELDS = [ MODE, RECLASS_FIELD, BURN_VAL ]
    FIELDS = BASE_FIELDS + RECLASS_FIELDS
    # FIELDS = BASE_FIELDS + RECLASS_FIELDS + [SC_MODE]
    DISPLAY_FIELDS = BASE_FIELDS
    
    def __init__(self,dict,feedback=None,child=None):
        # if self.SC_MODE not in dict:
        #     dict[self.SC_MODE] = 1
        if child is None:
            child = PondModel(feedback)
        super().__init__(dict,feedback=feedback,child=child)
        self.shortMode = False
        self.values = []
    

    # @classmethod
    # def fromDict(cls,dict,feedback=None):
    #     dict = utils.castDict(dict)
    #     return cls(dict,feedback=feedback)

    @classmethod
    def fromValues(cls, name, descr="", layer=None,
            base=None,baseLayer=None,extentFlag=True,
            mode=0, reclassField=None, burnVal=1,feedback=None):
        dict = { cls.NAME : name, cls.DESCR : descr, cls.BASE : base,
            cls.BASE_LAYER : baseLayer, cls.LAYER : layer,
            cls.EXTENT_FLAG : extentFlag, cls.MODE : mode,
            cls.RECLASS_FIELD : reclassField,
            cls.BURN_VAL : burnVal }
        return cls(dict, feedback=feedback)
        
    def __deepcopy__(self):
        item = ScenarioItem(copy.deepcopy(self.dict),
            feedback=self.feedback,child=self.child)
        return item
        
    def getName(self):
        return self.dict[self.NAME]
    def setName(self,val):
        self.dict[self.NAME] = val
    def getDescr(self):
        return self.dict[self.DESCR]
    def getBase(self):
        return self.dict[self.BASE]
    def setBase(self,val):
        self.dict[self.BASE] = val
    def getBaseLayer(self):
        return self.dict[self.BASE_LAYER]
    def getLayer(self):
        return self.dict[self.LAYER]
    def getExtentFlag(self):
        # if self.EXTENT_FLAG not in self.dict:
        #     self.dict[self.EXTENT_FLAG] = True
        return self.dict[self.EXTENT_FLAG]
    def getMode(self):
        return self.dict[self.MODE]
    def getBurnVal(self):
        return self.dict[self.BURN_VAL]
    def getBurnField(self):
        return self.dict[self.RECLASS_FIELD]
    # Mode checkers
    def isInitialState(self):
        return self.getMode() == self.INITIAL_STATE_MODE
    def isLanduseMode(self):
        return self.getMode() == self.LANDUSE_MODE
    def isVectorFixedMode(self):
        return self.getMode() == self.VECTOR_FIXED_MODE
    def isVectorFieldMode(self):
        return self.getMode() == self.VECTOR_FIELD_MODE
    def isRasterValuesMode(self):
        return self.getMode() == self.RASTER_VALUES_MODE
    def isRasterFixedMode(self):
        return self.getMode() == self.RASTER_FIXED_MODE
    def isFixedMode(self):
        return self.getMode() in [self.VECTOR_FIXED_MODE, self.RASTER_FIXED_MODE]
    def isValueMode(self):
        return self.getMode() in [self.VECTOR_FIELD_MODE, self.RASTER_VALUES_MODE]
    def isStackedMode(self):
        return self.getMode() not in [self.LANDUSE_MODE, self.INITIAL_STATE_MODE]
    def isVectorMode(self):
        return self.getMode() in [self.VECTOR_FIXED_MODE, self.VECTOR_FIELD_MODE]
    def isRasterMode(self):
        return self.getMode() in [self.RASTER_FIXED_MODE, self.RASTER_VALUES_MODE]
    def isPondMode(self):
        return self.getMode() in [self.PONDERATION_MODE]
        
    def isLeaf(self):
        return self.getBase() == None
    def useExtent(self):
        return self.getExtentFlag()
        
    def isVector(self):
        layerPath = self.getLayer()
        layer = qgsUtils.loadLayer(layerPath)
        if layer:
            return qgsUtils.isVectorLayer(layer)
        else:
            self.feedback.internal_error("Empty layer for scenario {}".format(self))
        
    def sameBurn(self,other):
        mode1, mode2 = self.getMode(), other.getMode()
        if mode1 != mode2:
            return False
        if mode1:
            return self.getBurnVal() == other.getBurnVal()
        else:
            return self.getBurnField() == other.getBurnField()
        
    def updateFromDlgItem(self,dlgItem):
        self.updateFromOther(dlgItem)
                
    # Mandatory to redefine it for import links reasons
    @classmethod
    def fromXML(cls,root,feedback=None):
        if cls.DESCR not in root.attrib:
            root.attrib[cls.DESCR] = ""
        o = cls.fromDict(root.attrib,feedback=feedback)
        utils.debug("fromXML result {}".format(o.dict))
        return o
    
    def computeValues(self,layer=None):
        if not layer:
            layerPath = self.getLayer()
            layer = qgsUtils.loadLayer(layerPath)
        if self.isVectorFieldMode():
            fieldname = self.getBurnField()
            self.values = qgsUtils.getLayerFieldUniqueValues(layer,fieldname)
        elif self.isRasterValuesMode():
            self.feedback.setProgressText("Fetching unique values")
            self.values = qgsTreatments.getRasterUniqueVals(layer,self.feedback)
            self.feedback.setProgress(100)
        else:
            self.values = []
        self.feedback.pushDebugInfo("computeValues {} = {}".format(self,self.values))
        
    def preDlg(self,dlg_item):
        self.feedback.pushDebugInfo(
            "preDlg {}".format(dlg_item))
        self.feedback.pushDebugInfo(
            "preDlgChild {}".format(dlg_item.child))
    def postDlg(self,dlg_item):
        self.feedback.pushDebugInfo(
            "postDlg {}".format(dlg_item))
        self.feedback.pushDebugInfo(
            "postDlgChild {}".format(dlg_item.child))
    def postDlgNew(self,dlg_item):
        self.feedback.pushDebugInfo(
            "postDlgNew {}".format(dlg_item))
            
    

class ScenarioDialog(QtWidgets.QDialog, SC_DIALOG):
    def __init__(self, parent, dlgItem, model=None, feedback=None):
        """Constructor."""
        super(ScenarioDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.newFlag = dlgItem is None
        self.reloadFlag = False
        self.feedback = feedback
        # if model is None:
        #     assert(False)
        self.scModel = model.scenarioModel
        self.frictionModel = model.frictionModel
        self.classModel = model.classModel
        self.setupUi(self)
        self.pondModel = dlgItem.child#PondModel(feedback=feedback)
        self.pondTable.setModel(self.pondModel)
        if hasattr(self, "pondLayerCombo"):
            self.pondLayerCombo.setFilters(qt_compatibility.RASTER_LAYER)
        self.layerComboDlg = qgsUtils.LayerComboDialog(self,
            self.scLayerCombo,self.scLayerButton)
        #self.layerComboDlg.setVectorMode()
        self.pondLayerComboDlg = qgsUtils.LayerComboDialog(self,
            self.pondLayerCombo,self.pondLayerButton)
        self.connectComponents()
        self.updateUi(dlgItem)
        self.reloadFlag = True
        self.values = []
        self.layer = None
        
    def connectComponents(self):
        self.scLayerCombo.layerChanged.connect(self.changeLayer)
        self.scFieldMode.clicked.connect(self.switchFieldMode)
        self.scFixedMode.clicked.connect(self.switchFixedMode)
        self.scField.setFilters(QgsFieldProxyModel.Numeric)
        self.scField.fieldChanged.connect(self.changeField)
        self.scBase.setModel(self.scModel)
        self.scMode.addItems([
            self.tr("Changement d'occupation du sol"),
            self.tr("Pondération des coefficients de friction")])
        self.scMode.currentIndexChanged.connect(
            lambda idx : self.stack.setCurrentIndex(idx))
        self.pondAddRowButton.clicked.connect(self.pondModel.addRow)
        self.pondRemoveRowButton.clicked.connect(self.removeSelectedPondItems)
        self.scModel.layoutChanged.emit()
        
    def switchBurnMode(self,fieldMode):
        self.scFixedMode.setChecked(not fieldMode)
        self.scFieldMode.setChecked(fieldMode)
        #self.scPerValue.setEnabled(fieldMode)
        self.scField.setEnabled(fieldMode)
        self.scBurnVal.setEnabled(not fieldMode)
    def switchFieldMode(self):
        self.switchBurnMode(True)
    def switchFixedMode(self):
        self.switchBurnMode(False)
        
    def changeLayer(self,layer):
        self.scField.setLayer(layer)
        # self.layer = layer
    def changeField(self,fieldname):
        layer = self.scLayerCombo.currentLayer()
        if fieldname:
            self.values = qgsUtils.getLayerFieldUniqueValues(layer,fieldname)
            self.feedback.pushDebugInfo("field values = " + str(self.values))
            nb_values = len(self.values)
            if nb_values > 5:
                feedbacks.paramError("Field {} contains {} unique values, is it ok or too much ?".format(fieldname,nb_values))
        else:
            self.values = []
        
    def errorDialog(self,msg):
        feedbacks.launchDialog(None,self.tr('Wrong parameter value'),msg)

    def removeSelectedPondItems(self):
        indexes = self.pondTable.selectedIndexes()
        # assert(False)
        for index in sorted(indexes, key=lambda i: i.row(), reverse=True):
            self.pondModel.removeSelectedRow(index.row())
        
    def showDialog(self):
        while self.exec():
            # Name
            name = self.scName.text()
            if not utils.isValidTag(name):
                feedbacks.launchDialog(self,self.tr("Wrong value"),
                    self.tr("Name '{}' contains invalid characters".format(name)))
                continue
            if self.newFlag and self.scModel.scExists(name):
                self.errorDialog(self.tr("Scenario already exists : " + name))
                continue
            if self.newFlag and self.frictionModel.importExists(name):
                self.errorDialog(self.tr("Import already exists : " + name))
                continue
            descr = self.scDescr.text()
            # base scenario
            base = self.scBase.currentText()
            self.feedback.pushDebugInfo("base = " + str(base))
            if base is None:
                self.errorDialog(self.tr("Empty base scenario"))
                continue
            # Mode
            landuseMode = self.scMode.currentIndex() == ScenarioItem.SC_LANDUSE_MODE
            fixedMode = self.scFixedMode.isChecked()
            # Layer
            if landuseMode:
                layer = self.scLayerCombo.currentLayer()
            else:
                layer = self.pondLayerCombo.currentLayer()
            if not layer:
                self.errorDialog(self.tr("Empty layer"))
                continue
            isVectorMode = qgsUtils.isVectorLayer(layer)
            layerPath = qgsUtils.pathOfLayer(layer)
            # Landuse parameters
            extentFlag = self.scExtentFlag.isChecked()
            shortMode = self.scShort.isChecked()
            scPerValueMode = self.scPerValue.isChecked()
            # Build item according to mode
            self.feedback.pushDebugInfo("fixedMode = " + str(fixedMode))
            if landuseMode:
                if fixedMode:
                    mode = ScenarioItem.VECTOR_FIXED_MODE if isVectorMode else ScenarioItem.RASTER_FIXED_MODE
                    burnVal = self.scBurnVal.text()
                    dlgItem = ScenarioItem.fromValues(name,descr=descr,
                        layer=layerPath,base=base,
                        mode=mode,burnVal=burnVal,extentFlag=extentFlag,
                        feedback=self.feedback)
                else:
                    if isVectorMode:
                        mode = ScenarioItem.VECTOR_FIELD_MODE
                        reclassField = self.scField.currentField()
                        if not reclassField:
                            self.errorDialog(self.tr("Empty field"))
                            continue
                    else:
                        mode = ScenarioItem.RASTER_VALUES_MODE
                    dlgItem = ScenarioItem.fromValues(name,descr=descr,
                        layer=layerPath,base=base,
                        mode=mode,reclassField=reclassField,extentFlag=extentFlag,
                        feedback=self.feedback)
            else:
                mode = ScenarioItem.PONDERATION_MODE
                dlgItem = ScenarioItem.fromValues(name,descr=descr,
                    layer=layerPath,base=base,
                    mode=mode,extentFlag=extentFlag,
                    feedback=self.feedback)
            # Pond Model
            self.feedback.pushDebugInfo("model1 {}".format(self.pondModel))
            dlgItem.setChild(self.pondModel)
            self.feedback.pushDebugInfo("child1 {}".format(dlgItem.child))
            self.feedback.pushDebugInfo("dlgItem1 {}".format(str(dlgItem)))
            # Compute values
            dlgItem.computeValues(layer=layer)
            # Check values count
            if dlgItem.isValueMode():
                nb_values = len(dlgItem.values)
                if nb_values == 0:
                    self.errorDialog(self.tr("No values found, please check that layer is not empty"))
                    continue
                elif nb_values > 40:
                    title = "High values count"
                    msg = "Scenario contains {} unique values to reclass, is it ok ?".format(nb_values)
                    reply = feedbacks.launchQuestionDialog(self,title,msg)
                    self.feedback.pushDebugInfo("reply {}".format(reply))
                    if reply == QtWidgets.QMessageBox.No:
                        continue
            self.values = dlgItem.values
            # dlgItem.values = self.values
            dlgItem.shortMode = shortMode
            return dlgItem
        return None

    def updateUi(self,dlgItem):
        # self.scBase.addItems(self.scenarioList)
        if dlgItem:
            self.feedback.pushDebugInfo("updateUI " + str(dlgItem.dict))
            # self.feedback.pushDebugInfo("updateUI child 1 " + str(dlgItem.reclassModel))
            scName = dlgItem.getName()
            self.scName.setText(scName)
            self.scDescr.setText(dlgItem.getDescr())
            self.scBase.setCurrentText(dlgItem.getBase())
            layer = dlgItem.getLayer()
            if layer and os.path.isfile(layer):
                self.layerComboDlg.setLayerPath(layer)
            self.scExtentFlag.setChecked(dlgItem.getExtentFlag())
            # Set burn val
            if dlgItem.isValueMode():
                self.switchBurnMode(True)
                self.scField.setField(dlgItem.getBurnField())
                burnVal = None
            elif dlgItem.isFixedMode():
                self.switchBurnMode(False)
                # burnVal = str(dlgItem.dict[ScenarioItem.BURN_VAL])
                classItem = self.classModel.getItemFromOrigin(scName)
                if classItem:
                    burnVal = classItem.getNewVal()
                else:
                    burnValStr = dlgItem.getBurnVal()
                    try:
                        burnVal =  int(burnValStr)
                    except TypeError:
                        burnVal = self.frictionModel.getFreeVal()
                self.feedback.pushDebugInfo("burnVal = " + str(burnVal))
                self.scBurnVal.setValue(burnVal)
            # Set stacked widget
            elif dlgItem.isPondMode():
                # Pond layer
                layer = dlgItem.getLayer()
                if layer and os.path.isfile(layer):
                    self.pondLayerComboDlg.setLayerPath(layer)
                # Pond model
                self.feedback.pushDebugInfo("child2 {}".format(dlgItem.child))
                self.pondTable.setModel(dlgItem.child)
                self.pondTable.model().layoutChanged.emit()
            # Index
            if dlgItem.isPondMode():
                self.scMode.setCurrentIndex(1)
                self.stack.setCurrentIndex(1)
            else:
                self.scMode.setCurrentIndex(0)
                self.stack.setCurrentIndex(0)
        else:
            burnVal = self.frictionModel.getFreeVal()
            self.scBurnVal.setValue(burnVal)
        # self.frictionModel.initComboCodes(self.scBurnVal,burnVal)

class ScenarioInitialStateDialog(QtWidgets.QDialog, SC_IS_DIALOG):
    def __init__(self, parent, dlgItem, feedback=None):
        """Constructor."""
        super(ScenarioInitialStateDialog, self).__init__(parent)
        self.feedback = feedback
        self.setupUi(self)
        self.updateUi(dlgItem)
                
    def updateUi(self,dlgItem):
        if dlgItem:
            self.scName.setText(dlgItem.getName())
            self.scDescr.setText(dlgItem.getDescr())
        else:
            assert(False)
        
    def showDialog(self):
        while self.exec():
            name = self.scName.text()
            if not utils.isValidTag(name):
                feedbacks.launchDialog(self,self.tr("Wrong value"),
                    self.tr("Name '{}' contains invalid characters".format(name)))
                continue
            descr = self.scDescr.text()
            dlgItem = ScenarioItem.fromValues(name=name,descr=descr,
                mode=3,layer=None,feedback=self.feedback)
            return dlgItem
        return None              

class PondItem(abstract_model.DictItem):
    
    MIN, MAX, COEFF = "MIN", "MAX", "COEFF"
    FIELDS = [MIN,MAX,COEFF]
    
    def __init__(self,dict=None,feedback=None):
        if not dict:
            dict = {self.MIN : 0, self.MAX : 0, self.COEFF : 1}
        super().__init__(dict)


class PondModel(abstract_model.DictModel):
    """Modèle table : intervalles [min, max] -> coefficient."""
    # HEADERS = ["Min", "Max", "Coefficient"]

    def __init__(self,feedback=None):
        itemClass = getattr(sys.modules[__name__],
            PondItem.__name__)
        super().__init__(itemClass=itemClass,
            fields=PondItem.FIELDS)
        self.feedback = feedback

    # def rowCount(self, parent=QtCore.QModelIndex()):
    #     return len(self.items)

    # def columnCount(self, parent=QtCore.QModelIndex()):
    #     return len(self.HEADERS)

    # def headerData(self, section, orientation, role=qt_compatibility.DISPLAY_ROLE):
    #     if role == qt_compatibility.DISPLAY_ROLE and orientation == qt_compatibility.HORIZONTAL:
    #         return self.HEADERS[section]
    #     return super().headerData(section, orientation, role)

    # def flags(self, index):
    #     return qt_compatibility.ITEM_IS_ENABLED | qt_compatibility.ITEM_IS_SELECTABLE |qt_compatibility.ITEM_IS_EDITABLE

    # def data(self, index, role=qt_compatibility.DISPLAY_ROLE):
    #     if not index.isValid() or role not in (qt_compatibility.DISPLAY_ROLE, qt_compatibility.EDIT_ROLE):
    #         return None
    #     return self.items[index.row()][index.column()]

    # def setData(self, index, value, role=qt_compatibility.EDIT_ROLE):
    #     if not index.isValid() or role != qt_compatibility.EDIT_ROLE:
    #         return False
    #     try:
    #         value = float(value)
    #     except (TypeError, ValueError):
    #         return False
    #     self.items[index.row()][index.column()] = value
    #     self.dataChanged.emit(index, index, [role])
    #     return True

    def addRow(self):
        self.beginInsertRows(QtCore.QModelIndex(),
            len(self.items), len(self.items))
        self.items.append(PondItem())
        self.endInsertRows()

    def removeSelectedRow(self, row):
        if 0 <= row < len(self.items):
            self.beginRemoveRows(QtCore.QModelIndex(),
                row, row)
            del self.items[row]
            self.endRemoveRows()
            self.layoutChanged.emit()

    def getRows(self):
        return self.items

    def setRows(self, rows):
        self.beginResetModel()
        self.items = rows
        self.endResetModel()