# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/species_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_speciesDialog(object):
    def setupUi(self, speciesDialog):
        speciesDialog.setObjectName("speciesDialog")
        speciesDialog.resize(427, 401)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(speciesDialog.sizePolicy().hasHeightForWidth())
        speciesDialog.setSizePolicy(sizePolicy)
        speciesDialog.setMinimumSize(QtCore.QSize(0, 366))
        speciesDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(speciesDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(speciesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 235))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.speciesID = QtWidgets.QLineEdit(self.frame)
        self.speciesID.setMinimumSize(QtCore.QSize(0, 20))
        self.speciesID.setMaximumSize(QtCore.QSize(16777215, 20))
        self.speciesID.setObjectName("speciesID")
        self.gridLayout_3.addWidget(self.speciesID, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.speciesFullName = QtWidgets.QLineEdit(self.frame)
        self.speciesFullName.setMinimumSize(QtCore.QSize(0, 20))
        self.speciesFullName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.speciesFullName.setObjectName("speciesFullName")
        self.gridLayout_3.addWidget(self.speciesFullName, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.speciesMaxDisp = QtWidgets.QSpinBox(self.frame)
        self.speciesMaxDisp.setMinimumSize(QtCore.QSize(0, 20))
        self.speciesMaxDisp.setMaximum(999999)
        self.speciesMaxDisp.setObjectName("speciesMaxDisp")
        self.gridLayout_3.addWidget(self.speciesMaxDisp, 2, 1, 1, 1)
        self.speciesDispUnit = QtWidgets.QComboBox(self.frame)
        self.speciesDispUnit.setMinimumSize(QtCore.QSize(0, 20))
        self.speciesDispUnit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.speciesDispUnit.setObjectName("speciesDispUnit")
        self.speciesDispUnit.addItem("")
        self.speciesDispUnit.addItem("")
        self.gridLayout_3.addWidget(self.speciesDispUnit, 2, 2, 1, 1)
        self.speciesDispDistMode = QtWidgets.QComboBox(self.frame)
        self.speciesDispDistMode.setMinimumSize(QtCore.QSize(0, 20))
        self.speciesDispDistMode.setMaximumSize(QtCore.QSize(16777215, 20))
        self.speciesDispDistMode.setObjectName("speciesDispDistMode")
        self.speciesDispDistMode.addItem("")
        self.speciesDispDistMode.addItem("")
        self.gridLayout_3.addWidget(self.speciesDispDistMode, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.speciesMinPatch = gui.QgsDoubleSpinBox(self.frame)
        self.speciesMinPatch.setMinimumSize(QtCore.QSize(87, 27))
        self.speciesMinPatch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.speciesMinPatch.setMaximum(999999.0)
        self.speciesMinPatch.setObjectName("speciesMinPatch")
        self.gridLayout_3.addWidget(self.speciesMinPatch, 4, 1, 1, 1)
        self.speciesPatchUnit = QtWidgets.QComboBox(self.frame)
        self.speciesPatchUnit.setMinimumSize(QtCore.QSize(0, 20))
        self.speciesPatchUnit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.speciesPatchUnit.setObjectName("speciesPatchUnit")
        self.speciesPatchUnit.addItem("")
        self.gridLayout_3.addWidget(self.speciesPatchUnit, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.speciesLanduse = QtWidgets.QComboBox(self.frame)
        self.speciesLanduse.setMinimumSize(QtCore.QSize(0, 20))
        self.speciesLanduse.setObjectName("speciesLanduse")
        self.gridLayout_3.addWidget(self.speciesLanduse, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 0, 1, 1)
        self.habitatCodes = gui.QgsCheckableComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.habitatCodes.sizePolicy().hasHeightForWidth())
        self.habitatCodes.setSizePolicy(sizePolicy)
        self.habitatCodes.setMinimumSize(QtCore.QSize(0, 20))
        self.habitatCodes.setObjectName("habitatCodes")
        self.gridLayout_3.addWidget(self.habitatCodes, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setEnabled(False)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 7, 0, 1, 1)
        self.speciesGroup = QtWidgets.QComboBox(self.frame)
        self.speciesGroup.setEnabled(False)
        self.speciesGroup.setMinimumSize(QtCore.QSize(0, 20))
        self.speciesGroup.setMaximumSize(QtCore.QSize(16777215, 20))
        self.speciesGroup.setObjectName("speciesGroup")
        self.gridLayout_3.addWidget(self.speciesGroup, 7, 1, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(speciesDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.speciesExtentLayer = gui.QgsFileWidget(self.groupBox)
        self.speciesExtentLayer.setEnabled(False)
        self.speciesExtentLayer.setMinimumSize(QtCore.QSize(0, 20))
        self.speciesExtentLayer.setObjectName("speciesExtentLayer")
        self.gridLayout_2.addWidget(self.speciesExtentLayer, 1, 2, 1, 1)
        self.speciesBufferMode = QtWidgets.QRadioButton(self.groupBox)
        self.speciesBufferMode.setChecked(True)
        self.speciesBufferMode.setObjectName("speciesBufferMode")
        self.gridLayout_2.addWidget(self.speciesBufferMode, 0, 0, 1, 1)
        self.speciesLayerMode = QtWidgets.QRadioButton(self.groupBox)
        self.speciesLayerMode.setObjectName("speciesLayerMode")
        self.gridLayout_2.addWidget(self.speciesLayerMode, 0, 2, 1, 1)
        self.speciesExtentBuffer = gui.QgsDoubleSpinBox(self.groupBox)
        self.speciesExtentBuffer.setMinimumSize(QtCore.QSize(100, 27))
        self.speciesExtentBuffer.setMaximumSize(QtCore.QSize(16777215, 20))
        self.speciesExtentBuffer.setProperty("value", 1.5)
        self.speciesExtentBuffer.setObjectName("speciesExtentBuffer")
        self.gridLayout_2.addWidget(self.speciesExtentBuffer, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(speciesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(speciesDialog)
        self.buttonBox.accepted.connect(speciesDialog.accept)
        self.buttonBox.rejected.connect(speciesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(speciesDialog)

    def retranslateUi(self, speciesDialog):
        _translate = QtCore.QCoreApplication.translate
        speciesDialog.setWindowTitle(_translate("speciesDialog", "Define new species"))
        self.label.setText(_translate("speciesDialog", "Species identifier"))
        self.label_2.setText(_translate("speciesDialog", "Species complete name"))
        self.label_3.setText(_translate("speciesDialog", "Dispersal distance"))
        self.speciesDispUnit.setItemText(0, _translate("speciesDialog", "meters"))
        self.speciesDispUnit.setItemText(1, _translate("speciesDialog", "cost unit"))
        self.speciesDispDistMode.setItemText(0, _translate("speciesDialog", "maximal distance"))
        self.speciesDispDistMode.setItemText(1, _translate("speciesDialog", "mean distance"))
        self.label_4.setText(_translate("speciesDialog", "Minimal patch area"))
        self.speciesPatchUnit.setItemText(0, _translate("speciesDialog", "ha"))
        self.label_5.setText(_translate("speciesDialog", "Land use layer"))
        self.label_8.setText(_translate("speciesDialog", "Habitat codes"))
        self.label_6.setText(_translate("speciesDialog", "Species group"))
        self.groupBox.setTitle(_translate("speciesDialog", "Extent"))
        self.speciesBufferMode.setText(_translate("speciesDialog", "Buffer"))
        self.speciesLayerMode.setText(_translate("speciesDialog", "Layer"))
        self.label_7.setText(_translate("speciesDialog", "* max capacity"))
from qgis import gui
