# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MitiConnect
                                 A QGIS plugin
 MitiConnect integrates ecological Connectivity in Mitigation Hierarchy
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-08-25
        git sha              : $Format:%H$
        copyright            : (C) 2021 by INRAE
        email                : mathieu.chailloux@inrae.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import sys

from qgis.core import QgsMessageLog

from ..qgis_lib_mc import abstract_model

class PondItem(abstract_model.DictItem):
    
    MIN, MAX, COEFF = "MIN", "MAX", "COEFF"
    FIELDS = [MIN,MAX,COEFF]
    
    def __init__(self,dict=None,feedback=None):
        if not dict:
            dict = {self.MIN : 0, self.MAX : 0, self.COEFF : 1}
        super().__init__(dict)

class PondModel(abstract_model.DictModel):
    """Modèle table : intervalles [min, max] -> coefficient."""
    # HEADERS = ["Min", "Max", "Coefficient"]

    def __init__(self,feedback=None):
        QgsMessageLog.logMessage(
            "sys.modules {} ".format(sys.modules),
            "Extensions")
        # itemClass = getattr(sys.modules[__name__],
        #     PondItem.__name__)
        # itemClass = PondItem.__class__
        super().__init__(itemClass=PondItem,
            fields=PondItem.FIELDS)
        self.feedback = feedback

    def addRow(self):
        self.beginInsertRows(QtCore.QModelIndex(),
            len(self.items), len(self.items))
        self.items.append(PondItem())
        self.endInsertRows()

    def removeSelectedRow(self, row):
        if 0 <= row < len(self.items):
            self.beginRemoveRows(QtCore.QModelIndex(),
                row, row)
            del self.items[row]
            self.endRemoveRows()
            self.layoutChanged.emit()

    def getRows(self):
        return self.items

    def setRows(self, rows):
        self.beginResetModel()
        self.items = rows
        self.endResetModel()

    def toProcessingMatrix(self):
        m = []
        for i in self.items:
            m.append(i.dict[PondItem.MIN])
            m.append(i.dict[PondItem.MAX])
            m.append(i.dict[PondItem.COEFF])
        return m